### ISSUE TITLE
Could not find gem 'content_for_in_controllers (>= 0) ruby'

### ISSUE THREAD

**Issue by cih997** [martin-denizet/redmine_message_issues#1]
During `rake db:migrate_plugins RAILS_ENV=production` I got this:

`Could not find gem 'content_for_in_controllers (>= 0) ruby' in the gems available on this machine.`

To solve this run `bundle install`.

**Comment by martin-denizet** [comment]
Yep, I didn't get it to work without that Gem, I need a make a README to detail the install.
