### ISSUE TITLE
Errors on plugin activate (odd number list for Hash, etc)

### ISSUE THREAD

**Issue by cih997** [martin-denizet/redmine_message_issues#2]
During `rake db:migrate_plugins RAILS_ENV=production` I got:

`rake aborted!
/var/www/aspexi-prod/redmine/plugins/redmine_message_issues/lib/redmine_message_issues/messages_controller_patch.rb:24: odd number list for Hash
...                  {controller: 'message_issues', action: 'ne...
                              ^
/var/www/aspexi-prod/redmine/plugins/redmine_message_issues/lib/redmine_message_issues/messages_controller_patch.rb:24: syntax error, unexpected ':', expecting '}'
...                  {controller: 'message_issues', action: 'ne...
                              ^
/var/www/aspexi-prod/redmine/plugins/redmine_message_issues/lib/redmine_message_issues/messages_controller_patch.rb:24: syntax error, unexpected ',', expecting '}'
...{controller: 'message_issues', action: 'new', message_id: @m...
                              ^
/var/www/aspexi-prod/redmine/plugins/redmine_message_issues/lib/redmine_message_issues/messages_controller_patch.rb:24: syntax error, unexpected ',', expecting '}'
...essage_issues', action: 'new', message_id: @message.id},
                              ^
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:359:in `require_or_load'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:313:in `depend_on'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:225:in `require_dependency'
/var/www/aspexi-prod/redmine/plugins/redmine_message_issues/init.rb:5:in `_callback_before_69'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:451:in `_run__629142126__prepare__4__callbacks'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:405:in `send'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:405:in `__run_callback'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:81:in `send'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/lib/gems/1.8/gems/actionpack-3.2.15/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
/var/lib/gems/1.8/gems/actionpack-3.2.15/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/application/finisher.rb:47
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/initializable.rb:55:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `each'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/application.rb:136:in `initialize!'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:30:in `send'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/www/aspexi-prod/redmine/config/environment.rb:14
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.15/lib/active_support/dependencies.rb:251:in `require'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/application.rb:103:in `require_environment!'
/var/lib/gems/1.8/gems/railties-3.2.15/lib/rails/application.rb:305:in `initialize_tasks'
Tasks: TOP => db:migrate_plugins => redmine:plugins:migrate => environment
(See full trace by running task with --trace)`

**Comment by martin-denizet** [comment]
What's your Redmine/Ruby versions please?

**Comment by cih997** [comment]
Environment:
  Redmine version                2.4.1.stable
  Ruby version                   1.8.7
  Rails version                  3.2.15

**Comment by martin-denizet** [comment]
Could you please test that latest version? I was using Ruby 1.9 syntax.

**Comment by cih997** [comment]
Plugin works fine now. User roles seems to be working fine as well.
