### ISSUE TITLE
Message list & link on issue page

### ISSUE THREAD

**Issue by cih997** [martin-denizet/redmine_message_issues#3]
At the moment I can see issues list & links on message page. I would need to see linked messages list & links on ISSUE PAGE.

I do not need to add / edit / remove messages on issue page. Just a list & links.

**Comment by martin-denizet** [comment]
Please, try the latest develop version.

**Comment by cih997** [comment]
Amazing stuff. It's full functional now.

**Comment by cih997** [comment]
This was broken for me for Redmine 3.4.3. I have restored some files removed by @martin-denizet previously and now I can see list of messages assigned to the issue on issue page.
