### ISSUE TITLE
Disable ability to link empty issue

### ISSUE THREAD

**Issue by cih997** [martin-denizet/redmine_message_issues#4]
At the moment user can link empty issue. There is "Issue deleted" on list.

**Comment by martin-denizet** [comment]
Was fixed a while back, I forgot to close the issue.
When the issue doesn't exist, an error message is displayed:
![image](https://cloud.githubusercontent.com/assets/522331/4439501/ed9c3a28-47b8-11e4-9478-be0f8ea6f77f.png)
